---
- hosts: all
  gather_facts: true
  become: yes
  roles:
  vars:
    user: attunity
    group: attunity
    noncredentials: true
    verbose: true
    data: /opt/attunity/replicate-data
    prefix: /opt/attunity/
  environment:
    variables: arep_login.sh
    settings: site_are_login.sh
    configuration: areplicate_arep_login.sh
  tasks:
  - name: "Install unzip"
    yum:
      name:
        - unzip
      state: present

  - name: “see if directory exist”
    file:
      path: /opt/attunity/
      state: directory

  - name: "Download Package"
    get_url:
      url: https://test-replicate.s3-us-gov-west-1.amazonaws.com/areplicate-7.0.0-402.x86_64.tar
      dest: /opt/attunity/
      mode: '0755'

  - name: “Unpack Package”
    unarchive:
      src: AttunityReplicate_2021_5_0_Linux_X64.tar.gz
      dest: /opt/attunity/
      remote_src: yes


  - name: “Install Qlik Replicate”
    yum:
      name: /opt/attunity/areplicate-2021.5.0-745.x86_64.rpm
      state: present

  - name: “start service”
    command: /opt/attunity/replicate/bin/areplicate start


